E2Helper.Descriptions["identityMatrix(n)"] = "Returns an nxn identity matrix."
E2Helper.Descriptions["newMatrix(nn)"] = "Returns a new nxm matrix with all entries set to 0."
E2Helper.Descriptions["addMatrix(cmcm)"] = "Returns a new nxm matrix with all entries set to 0."
E2Helper.Descriptions["scalarMultiply(cmn)"] = "Multiplies every entry in the matrix by a constant and returns the result as a new matrix."
E2Helper.Descriptions["matrixMultiply(cmcm)"] = "Multiplies the first matrix by the second and returns the result as a new matrix."
E2Helper.Descriptions["transposeMatrix(cm)"] = "Returns a new matrix equal to the given matrix transposed."
E2Helper.Descriptions["determinant(cm)"] = "Returns the determinant of a given matrix."
E2Helper.Descriptions["inverse(cm)"] = "Returns a new matrix equal to the inverse of the given matrix, if that matrix is invertible."


E2Helper.Descriptions["entryExists(cm:nn)"] = "Returns whether entry i,j exists in this matrix."
E2Helper.Descriptions["get(cm:nn)"] = "Returns (i,j)th entry of this matrix."
E2Helper.Descriptions["set(cm:nnn)"] = "Sets the (i,j)th entry of this matrix to the first parameter."
E2Helper.Descriptions["rows(cm:)"] = "Returns the number of rows in this matrix."
E2Helper.Descriptions["columns(cm:)"] = "Returns the number of columns in this matrix."